MVC/MVCAgenda/Models/Compromisso.cs
namespace MVCAgenda.Models
{
    public class Compromisso
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public DateTime Data { get; set; }
        public Contato Contato { get; set; }
    }
}

MVC/MVCAgenda/Models/Contato .cs
namespace MVCAgenda.Models
{
    public class Contato
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Fone { get; set; }
    }
}

MVC/MVCAgenda/Models/ErrorViewModel.cs
namespace MVCAgenda.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/MVCAgenda/Controllers/CompromissoController.cs
using MVCAgenda.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MVCAgenda.Controllers
{
    public class CompromissoController : Controller
    {
        public IActionResult Index()
        {
            return View(Dados.Db.compromissos);
        }

        [HttpGet]
        public IActionResult Create()
        {
            List<SelectListItem> Contatos = new List<SelectListItem>();
            Contatos = MVCAgenda.Dados.Db.contatos.Select(c => new SelectListItem() 
            { Text = c.Email, Value = c.Id.ToString() }).ToList();
            ViewBag.Contatos = Contatos;
            return View();
        }

        [HttpPost]
        public IActionResult Create(Compromisso compromisso)
        {
            compromisso.Id = Dados.Db.compromissos.Max(c => c.Id) + 1;
            Contato ct = Dados.Db.contatos.FirstOrDefault(c => c.Id == compromisso.Contato.Id);
            compromisso.Contato = ct;
            Dados.Db.compromissos.Add(compromisso);
            return RedirectToAction("Index");
        }
    }
}

MVC/MVCAgenda/Views/Compromisso/Create.cshtml
@model MVCAgenda.Models.Compromisso
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Contato" class="control-label"></label>
                <select asp-for="Contato.Id" asp-items="@ViewBag.contatos" class="form-control"></select>
                <span asp-validation-for="Contato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVC/MVCAgenda/Views/Compromisso/Index.cshtml
@model IEnumerable<MVCAgenda.Models.Compromisso>
@{
   ViewData["title"] = "Compromissos";
}

<h2 class="text-center">@ViewData["title"]</h2>

@Html.ActionLink("Create","Create")

<hr />

<table class="table">
    <thead class="table-info">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Id)</th>
            <th>@Html.DisplayNameFor(model => model.Descricao)</th>
            <th>@Html.DisplayNameFor(model => model.Data)</th>
            <th>@Html.DisplayNameFor(model => model.Contato.Email)</th>
        </tr>
        <tbody class="table-dark">
            @foreach(var item in Model)
            {
            <tr>
                <td>@Html.DisplayFor(model => item.Id)</td>
                <td>@Html.DisplayFor(model => item.Descricao)</td>
                <td>@Html.DisplayFor(model => item.Data)</td>
                <td>@Html.DisplayFor(model => item.Contato.Email)</td>
            </tr>
            }
        </tbody>
    </thead>
</table>

MVC/MVCAgenda/Views/Contato/Create.cshtml
@model MVCAgenda.Models.Contato
@{
    ViewData["Title"] = "Create";
}
<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fone" class="control-label"></label>
                <input asp-for="Fone" class="form-control" />
                <span asp-validation-for="Fone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

MVC/MVCAgenda/Views/Contato/Delete.cshtml
@model MVCAgenda.Models.Contato
@{
    ViewData["title"] = "Delete";
}
<hr />
<div>
    <p>Deseja deletar este contato permanentemente?</p>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Fone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Fone)
        </dd>
    </dl>
    <form asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index">Back to List</a>
    </form>

</div>

MVC/MVCAgenda/Views/Contato/Edit.cshtml
@model MVCAgenda.Models.Contato
@{
    ViewData["Title"] = "Edit";
}
<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fone" class="control-label"></label>
                <input asp-for="Fone" class="form-control" />
                <span asp-validation-for="Fone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MVC/MVCAgenda/Views/Contato/Index.cshtml
@model IEnumerable<MVCAgenda.Models.Contato>
@{
    ViewData["Title"] = "Contatos";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<p>
    <a class="link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" asp-action="Create">Create</a>
</p>
<div>
    <table class="table">
        <thead class="table-info">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fone)
                </th>
                <th>

                </th>

            </tr>
        </thead>

        <tbody>
            @foreach(var item in Model)
            {
                <tr class="table-dark">
                    <td>
                        @Html.DisplayFor(model => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Fone)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new {Id = item.Id} )       |
                        @Html.ActionLink("Delete", "Delete", new {Id = item.Id})
                    </td>
                    
                </tr>
            }
        </tbody>
    </table>
</div>

MVC/MVCAgenda/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC/MVCAgenda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgendaMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AgendaMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AgendaMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compromisso" asp-action="Index">Compromissos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AgendaMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>